language: c
script:
  - echo 'ADD . /home/opam/qubes-mirage-firewall' >> Dockerfile
  - echo 'RUN sudo chown -R opam /home/opam/qubes-mirage-firewall' >> Dockerfile
  - docker build -t qubes-mirage-firewall .
  - docker run --rm -i qubes-mirage-firewall
sudo: required
dist: trusty
