name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: ./build-with-docker.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mirage-firewall.tar.bz2
          path: mirage-firewall.tar.bz2
